// @@OTEL_USINGS@@
using System.Diagnostics;
using System.Net.Http.Json;
using System.Runtime.InteropServices;
using Microsoft.EntityFrameworkCore;
using OpenTelemetry.Trace;

// OtelProbe — variant 07-otel-config-tester.
//
// This is a TEMPLATE. scripts/render.mjs replaces the two @@OTEL_...@@ markers
// with the output of the OTel Tracing Configurator (configurator/*.html) and
// writes the result to build/<config>/app/Program.cs. Everything else in this
// file is the same for every configuration, so the only difference between two
// runs is the OpenTelemetry wiring under test.
//
// The app is a small shop. It exists to produce the kinds of spans the
// configurator has options for, and to produce traces that are more than one
// span deep:
//
//   POST /api/orders   the main flow, one trace, typically 12-20 spans:
//     SERVER  POST /api/orders
//       INTERNAL "Validate order"            (custom ActivitySource)
//         CLIENT  SELECT customers           (EF Core)
//       CLIENT  GET /api/pricing/{sku}       (HttpClient, one per line, in PARALLEL)
//         SERVER  GET /api/pricing/{sku}
//           CLIENT  SELECT products          (EF Core)
//           INTERNAL "Apply discount rules"  (custom, with a span event)
//       INTERNAL "Reserve stock"             (custom)
//         CLIENT  UPDATE products            (EF Core, one per line)
//         CLIENT  INSERT orders/order_lines  (EF Core)
//       CLIENT  POST /api/notifications      (HttpClient)
//         SERVER  POST /api/notifications
//           CLIENT  INSERT notifications     (EF Core)
//
//   Plus single-purpose endpoints for filters, exceptions, span limits and
//   outgoing-call filters. The list is in README.md and in scripts/06-probe.sh.
//
//   GET /  is a test page (wwwroot/index.html) with buttons for all of it.
//
// Which spans actually appear depends entirely on the generated configuration.
// For example: without AddEntityFrameworkCoreInstrumentation() there are no
// SELECT/INSERT spans; without the custom source in AddSource(...) there are no
// "Validate order" spans; with AddAspNetCoreInstrumentation() off, every
// outgoing HttpClient call becomes its own root span.
//
// The custom ActivitySource name comes from PROBE_SOURCE. render.mjs sets it to
// the first name in the configuration's "ActivitySource names" list, so the
// custom spans are listened to exactly when the configuration says so.

var builder = WebApplication.CreateBuilder(args);

Probe.Init(
    sourceName: builder.Configuration["PROBE_SOURCE"] ?? "OtelProbe",
    runId: builder.Configuration["PROBE_RUN_ID"] ?? "local",
    configName: builder.Configuration["PROBE_CONFIG_NAME"] ?? "local");

// Calls to "ourselves" go through the Kubernetes service, like a call to a
// second service would. The trace then shows CLIENT -> SERVER pairs.
var selfUrl = builder.Configuration["PROBE_SELF_URL"] ?? "http://localhost:8080";

// --- database ----------------------------------------------------------------
// SQLite in a FILE under /tmp (not in-memory, unlike variant 06): the order
// flow, the parallel pricing calls and the background worker write and read
// at the same time. In-memory shared-cache SQLite answers concurrent access
// with "database table is locked" instead of waiting. A file in WAL mode lets
// readers run while one writer writes, and writers wait (busy timeout) instead
// of failing. The file is deleted at startup: every pod starts empty.
var dbPath = builder.Configuration["PROBE_DB_PATH"] ?? Path.Combine(Path.GetTempPath(), "shop.db");
builder.Services.AddDbContext<ShopDb>(o => o.UseSqlite($"Data Source={dbPath};Default Timeout=30"));

builder.Services.AddHttpClient("self", c =>
{
    c.BaseAddress = new Uri(selfUrl);
    c.Timeout = TimeSpan.FromSeconds(15);
});
builder.Services.AddHttpClient("outside", c => c.Timeout = TimeSpan.FromSeconds(5));

// CORS so that OPTIONS preflight requests get a real answer (and a span,
// unless the configuration's "Drop CORS preflight" filter removes it).
builder.Services.AddCors(o => o.AddDefaultPolicy(p => p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));

builder.Services.AddHostedService<StockSyncWorker>();

// ============================================================================
// Generated by the OTel Tracing Configurator. Do not edit build/*/Program.cs by
// hand; change the configuration and run scripts/run.sh again.
// @@OTEL_TRACING@@
// ============================================================================

var app = builder.Build();

app.UseCors();

// For the test page (wwwroot/index.html): tell the caller which trace this
// request belongs to, and whether its span is recorded. Recorded=false means
// the span exists in the process but will not be exported (dropped by a
// Filter, or not sampled). No header at all means there is no server activity:
// ASP.NET Core instrumentation is off. Adds nothing to the telemetry itself.
app.Use(async (ctx, next) =>
{
    if (Activity.Current is { } a)
    {
        ctx.Response.Headers["X-Trace-Id"] = a.TraceId.ToHexString();
        ctx.Response.Headers["X-Trace-Recorded"] = a.Recorded ? "true" : "false";
    }
    await next();
});

app.UseDefaultFiles(); // "/" -> /index.html, the test page
app.UseStaticFiles();  // wwwroot/: index.html, /css/site.css, /js/site.js, /favicon.ico

// --- database setup ----------------------------------------------------------
// With EF instrumentation on, this already produces db spans that have no
// parent request (root spans). That is expected: startup work is not a request.
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<ShopDb>();
    db.Database.EnsureDeleted();
    db.Database.EnsureCreated();
    db.Database.ExecuteSqlRaw("PRAGMA journal_mode=WAL;");
    Seed.Run(db);
}

// --- noise endpoints ---------------------------------------------------------
// These are what the configurator's Filter options are for. /health is also the
// readiness probe in k8s/, so with no filter there is one span every 10 s.
app.MapGet("/health", () => Results.Ok("ok"));
app.MapGet("/healthz", () => Results.Ok("ok"));
app.MapGet("/ready", () => Results.Ok("ok"));
app.MapGet("/alive", () => Results.Ok("ok"));
app.MapGet("/metrics", () => Results.Text("# no metrics here, this endpoint only exists to be filtered\n"));

// --- the shop ----------------------------------------------------------------
app.MapGet("/api/products", async (ShopDb db) =>
    Results.Ok(await db.Products.AsNoTracking().OrderBy(p => p.Sku).ToListAsync()));

// A route with a dot in it. The configurator's "drop any path with a file
// extension" filter (Path.HasExtension) also drops this one — a real API route.
app.MapGet("/api/v1.0/products", async (ShopDb db) =>
    Results.Ok(await db.Products.AsNoTracking().OrderBy(p => p.Sku).Take(5).ToListAsync()));

app.MapGet("/api/products/{sku}", async (string sku, ShopDb db) =>
{
    Activity.Current?.SetTag("shop.sku", sku);
    var p = await db.Products.AsNoTracking().FirstOrDefaultAsync(x => x.Sku == sku);
    return p is null ? Results.NotFound() : Results.Ok(p);
});

// Called by the order flow for every line (in parallel), and callable directly.
app.MapGet("/api/pricing/{sku}", async (string sku, ShopDb db) =>
{
    Activity.Current?.SetTag("shop.sku", sku);
    var p = await db.Products.AsNoTracking()
        .Where(x => x.Sku == sku)
        .Select(x => new { x.Sku, x.Price, x.Category })
        .FirstOrDefaultAsync();
    if (p is null) return Results.NotFound();

    using var rules = Probe.Source.StartActivity("Apply discount rules");
    await Task.Delay(Random.Shared.Next(5, 30)); // some visible duration
    var discount = p.Category == "tools" ? 0.10 : 0.0;
    rules?.SetTag("shop.category", p.Category);
    rules?.SetTag("shop.discount", discount);
    rules?.AddEvent(new ActivityEvent("discount.evaluated", tags: new ActivityTagsCollection
    {
        ["rule"] = p.Category == "tools" ? "tools-10-percent" : "none",
    }));
    return Results.Ok(new PriceResponse(p.Sku, Math.Round(p.Price * (1 - discount), 2), discount));
});

app.MapPost("/api/orders", async (OrderRequest req, ShopDb db, IHttpClientFactory http) =>
{
    var span = Activity.Current;
    span?.SetTag("shop.customer_id", req.CustomerId);
    span?.SetTag("shop.line_count", req.Lines.Count);

    // 1. Validate: the customer exists and the order is well-formed.
    Customer? customer;
    using (var validate = Probe.Source.StartActivity("Validate order"))
    {
        customer = await db.Customers.AsNoTracking().FirstOrDefaultAsync(c => c.Id == req.CustomerId);
        if (customer is null || req.Lines.Count == 0 || req.Lines.Any(l => l.Quantity <= 0))
        {
            var reason = customer is null ? "unknown_customer" : "invalid_lines";
            validate?.AddEvent(new ActivityEvent("validation.failed", tags: new ActivityTagsCollection { ["reason"] = reason }));
            span?.SetTag("shop.outcome", reason);
            return customer is null ? Results.NotFound(new { error = reason }) : Results.BadRequest(new { error = reason });
        }
        validate?.AddEvent(new ActivityEvent("validation.passed"));
        span?.SetTag("shop.customer_tier", customer.Tier);
    }

    // 2. Price every line through the pricing endpoint, all lines in parallel.
    var self = http.CreateClient("self");
    var skus = req.Lines.Select(l => l.Sku).Distinct().ToList();
    var priced = await Task.WhenAll(skus.Select(async sku =>
    {
        using var resp = await self.GetAsync($"/api/pricing/{Uri.EscapeDataString(sku)}");
        return resp.IsSuccessStatusCode ? await resp.Content.ReadFromJsonAsync<PriceResponse>() : null;
    }));
    if (priced.Any(p => p is null))
    {
        span?.SetTag("shop.outcome", "unknown_sku");
        return Results.BadRequest(new { error = "unknown_sku" });
    }
    var prices = priced.ToDictionary(p => p!.Sku, p => p!.UnitPrice);

    // 3. Reserve stock and store the order, in one transaction.
    var orderId = Guid.NewGuid().ToString("N")[..12];
    span?.SetTag("shop.order_id", orderId);
    double total;
    using (var reserve = Probe.Source.StartActivity("Reserve stock"))
    {
        await using var tx = await db.Database.BeginTransactionAsync();
        foreach (var line in req.Lines)
        {
            var qty = line.Quantity;
            var updated = await db.Products
                .Where(p => p.Sku == line.Sku && p.Stock >= qty)
                .ExecuteUpdateAsync(s => s.SetProperty(p => p.Stock, p => p.Stock - qty));
            if (updated == 0)
            {
                await tx.RollbackAsync();
                reserve?.AddEvent(new ActivityEvent("stock.insufficient", tags: new ActivityTagsCollection
                {
                    ["sku"] = line.Sku,
                    ["requested"] = qty,
                }));
                span?.SetTag("shop.outcome", "insufficient_stock");
                return Results.Conflict(new { error = "insufficient_stock", sku = line.Sku });
            }
        }

        total = Math.Round(req.Lines.Sum(l => prices[l.Sku] * l.Quantity), 2);
        db.Orders.Add(new Order
        {
            Id = orderId,
            CustomerId = req.CustomerId,
            CreatedAtUtc = DateTime.UtcNow,
            Total = total,
            Status = "placed",
            Lines = req.Lines.Select(l => new OrderLine { Sku = l.Sku, Quantity = l.Quantity, UnitPrice = prices[l.Sku] }).ToList(),
        });
        await db.SaveChangesAsync();
        await tx.CommitAsync();
        reserve?.AddEvent(new ActivityEvent("stock.reserved", tags: new ActivityTagsCollection { ["lines"] = req.Lines.Count }));
    }
    span?.SetTag("shop.order_total", total);

    // 4. Notify. A third level: CLIENT -> SERVER -> db INSERT.
    using (var notify = await self.PostAsJsonAsync("/api/notifications", new NotificationRequest(orderId, "email")))
    {
        span?.SetTag("shop.notified", notify.IsSuccessStatusCode);
    }

    span?.SetTag("shop.outcome", "placed");
    return Results.Created($"/api/orders/{orderId}", new { orderId, total });
});

app.MapGet("/api/orders/{id}", async (string id, ShopDb db) =>
{
    Activity.Current?.SetTag("shop.order_id", id);
    // Include -> one SQL statement with a JOIN.
    var order = await db.Orders.AsNoTracking().Include(o => o.Lines).FirstOrDefaultAsync(o => o.Id == id);
    return order is null ? Results.NotFound() : Results.Ok(order);
});

app.MapGet("/api/customers/{id}/orders", async (string id, int? limit, ShopDb db) =>
{
    Activity.Current?.SetTag("shop.customer_id", id);
    var orders = await db.Orders.AsNoTracking()
        .Where(o => o.CustomerId == id)
        .OrderByDescending(o => o.CreatedAtUtc)
        .Take(Math.Clamp(limit ?? 20, 1, 100))
        .Include(o => o.Lines)
        .ToListAsync();
    Activity.Current?.SetTag("shop.orders_returned", orders.Count);
    return Results.Ok(orders);
});

app.MapPost("/api/notifications", async (NotificationRequest req, ShopDb db) =>
{
    Activity.Current?.SetTag("shop.order_id", req.OrderId);
    await Task.Delay(Random.Shared.Next(10, 40)); // pretend to talk to a mail gateway
    db.Notifications.Add(new Notification { OrderId = req.OrderId, Channel = req.Channel, CreatedAtUtc = DateTime.UtcNow });
    await db.SaveChangesAsync();
    return Results.Accepted();
});

// --- failures ----------------------------------------------------------------
// Unhandled exception inside a custom span. Tests RecordException and
// EnrichWithException on the SERVER span, and shows what a custom span does
// with an exception it does not catch (nothing: it just ends).
app.MapGet("/api/fail", () =>
{
    using var step = Probe.Source.StartActivity("Risky step");
    throw new InvalidOperationException("Probe failure: thrown on purpose by /api/fail");
});

// The failure one level down: CLIENT span gets HTTP 500 (no exception on the
// client span: HttpClient does not throw for a 500), then EnsureSuccessStatusCode
// throws in THIS handler, so both SERVER spans end with an exception.
app.MapGet("/api/fail/nested", async (IHttpClientFactory http) =>
{
    using var resp = await http.CreateClient("self").GetAsync("/api/fail");
    resp.EnsureSuccessStatusCode();
    return Results.Ok();
});

// A network-level failure: DNS for the reserved .invalid domain always fails.
// Here the CLIENT span carries the exception (HttpClient RecordException /
// EnrichWithException). The exception is caught, so the SERVER span ends as a
// plain 502 without an exception event.
app.MapGet("/api/fail/unreachable", async (IHttpClientFactory http) =>
{
    try
    {
        using var resp = await http.CreateClient("outside").GetAsync("http://no-such-host.invalid/");
        return Results.Ok();
    }
    catch (HttpRequestException ex)
    {
        return Results.Problem(ex.Message, statusCode: 502);
    }
});

// A database error: the db span ends with an error, the request with a 500.
app.MapGet("/api/fail/db", async (ShopDb db) =>
{
    await db.Database.ExecuteSqlRawAsync("SELECT * FROM no_such_table");
    return Results.Ok();
});

// --- outgoing-call filters -----------------------------------------------------
// Two outgoing calls that the configurator's FilterHttpRequestMessage defaults
// target: one to the collector's host ("Hosts to drop" placeholder is
// otel-collector) and one to a /health path ("Path prefixes to drop" default).
app.MapGet("/api/diagnostics/ping", async (IHttpClientFactory http) =>
{
    var results = new Dictionary<string, int>();
    async Task Call(string key, HttpClient c, string url)
    {
        try { using var r = await c.GetAsync(url); results[key] = (int)r.StatusCode; }
        catch (HttpRequestException) { results[key] = -1; }
    }
    await Call("collector", http.CreateClient("outside"), "http://otel-collector:4318/");
    await Call("self_health", http.CreateClient("self"), "/health");
    return Results.Ok(results);
});

// --- span size ---------------------------------------------------------------
// Everything the "Span limits" options cap, on purpose and far over the SDK
// defaults: one very long attribute value, many attributes, many events with
// many attributes each, and a custom child span with many links.
//   /api/wide?attrs=200&events=40&links=40&valueLength=20000
app.MapGet("/api/wide", (int? attrs, int? events, int? links, int? valueLength) =>
{
    int nAttrs = Math.Clamp(attrs ?? 200, 0, 1000), nEvents = Math.Clamp(events ?? 40, 0, 1000);
    int nLinks = Math.Clamp(links ?? 40, 0, 1000), len = Math.Clamp(valueLength ?? 20000, 0, 1_000_000);

    static IEnumerable<KeyValuePair<string, object?>> Tags(int n) =>
        Enumerable.Range(0, n).Select(j => new KeyValuePair<string, object?>($"k{j:D2}", j));

    void Fill(Activity? a)
    {
        if (a is null) return;
        a.SetTag("probe.long_value", new string('x', len));
        for (var i = 0; i < nAttrs; i++) a.SetTag($"probe.attr.{i:D3}", $"value-{i}");
        for (var i = 0; i < nEvents; i++)
            a.AddEvent(new ActivityEvent($"probe.event.{i:D3}", tags: new ActivityTagsCollection(Tags(20))));
    }

    var server = Activity.Current;
    Fill(server);

    var linkList = Enumerable.Range(0, nLinks).Select(_ => new ActivityLink(
        new ActivityContext(ActivityTraceId.CreateRandom(), ActivitySpanId.CreateRandom(), ActivityTraceFlags.Recorded),
        new ActivityTagsCollection(Tags(20)))).ToList();
    using (var wide = Probe.Source.StartActivity("Wide span", ActivityKind.Internal,
               parentContext: server?.Context ?? default, links: linkList))
    {
        Fill(wide);
    }

    return Results.Ok(new { attrs = nAttrs, events = nEvents, links = nLinks, valueLength = len });
});

// A long SQL statement: an IN list of n literals, ~11 characters per entry.
// With OTEL_SEMCONV_STABILITY_OPT_IN=database the text lands in db.query.text
// (literals replaced by '?', still long); without it in db.statement.
// This is what OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT cuts.
app.MapGet("/api/db/long-query", async (int? n, ShopDb db) =>
{
    var count = Math.Clamp(n ?? 1500, 1, 20000);
    var list = string.Join(", ", Enumerable.Range(0, count).Select(i => $"'X-{i:D6}'"));
    var sql = $"SELECT * FROM products WHERE sku IN ({list}) OR sku = 'SKU-001'";
    var rows = await db.Products.FromSqlRaw(sql).AsNoTracking().ToListAsync();
    Activity.Current?.SetTag("probe.sql_length", sql.Length);
    return Results.Ok(new { sqlLength = sql.Length, rows = rows.Count });
});

// --- probe control -----------------------------------------------------------
// ForceFlush: the batch exporter otherwise sends every few seconds. The probe
// script calls this last, so everything is in ClickHouse when it finishes.
// (This request's own span is exported with the NEXT batch.)
app.MapPost("/probe/flush", (IServiceProvider sp) =>
{
    var tp = sp.GetService<TracerProvider>();
    var ok = tp?.ForceFlush(10_000) ?? false;
    return Results.Ok(new { flushed = ok, tracerProvider = tp is not null });
});

app.MapGet("/probe/info", () => Results.Ok(new
{
    Probe.RunId,
    Probe.ConfigName,
    activitySource = Probe.Source.Name,
    framework = RuntimeInformation.FrameworkDescription,
    selfUrl,
}));

app.Run();

// =============================================================================

static class Probe
{
    public static ActivitySource Source { get; private set; } = new("OtelProbe");
    public static string RunId { get; private set; } = "";
    public static string ConfigName { get; private set; } = "";

    public static void Init(string sourceName, string runId, string configName)
    {
        Source = new ActivitySource(sourceName);
        RunId = runId;
        ConfigName = configName;
    }
}

// A background job with no HTTP request around it. With the custom source
// listened to, each run is a ROOT span "Stock sync" with db children. Without
// it, the db spans themselves become separate root spans (or nothing, without
// EF instrumentation). Every 30 s; PROBE_WORKER_SECONDS=0 switches it off.
sealed class StockSyncWorker(IServiceScopeFactory scopes, IConfiguration config, ILogger<StockSyncWorker> log) : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stop)
    {
        var seconds = int.TryParse(config["PROBE_WORKER_SECONDS"], out var s) ? s : 30;
        if (seconds <= 0) return;
        await Task.Delay(TimeSpan.FromSeconds(5), stop);
        while (!stop.IsCancellationRequested)
        {
            try
            {
                using var run = Probe.Source.StartActivity("Stock sync", ActivityKind.Internal);
                using var scope = scopes.CreateScope();
                var db = scope.ServiceProvider.GetRequiredService<ShopDb>();
                var low = await db.Products.CountAsync(p => p.Stock < 100, stop);
                var restocked = await db.Products.Where(p => p.Stock < 100)
                    .ExecuteUpdateAsync(u => u.SetProperty(p => p.Stock, p => p.Stock + 500), stop);
                run?.SetTag("shop.low_stock_products", low);
                run?.SetTag("shop.restocked", restocked);
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                log.LogWarning(ex, "Stock sync failed");
            }
            await Task.Delay(TimeSpan.FromSeconds(seconds), stop);
        }
    }
}

static class Seed
{
    static readonly string[] Categories = ["tools", "garden", "kitchen"];
    static readonly string[] Tiers = ["standard", "standard", "standard", "gold", "platinum"];

    public static void Run(ShopDb db)
    {
        for (var i = 1; i <= 50; i++)
            db.Customers.Add(new Customer { Id = $"C{i:D3}", Name = $"Customer {i}", Tier = Tiers[i % Tiers.Length] });
        for (var i = 1; i <= 30; i++)
            db.Products.Add(new Product
            {
                Sku = $"SKU-{i:D3}",
                Name = $"Product {i}",
                Category = Categories[i % Categories.Length],
                Price = Math.Round(4.99 + i * 3.1, 2),
                Stock = 1000,
            });
        db.SaveChanges();
    }
}

record OrderRequest(string CustomerId, List<OrderLineRequest> Lines);
record OrderLineRequest(string Sku, int Quantity);
record PriceResponse(string Sku, double UnitPrice, double Discount);
record NotificationRequest(string OrderId, string Channel);

// double, not decimal: the SQLite provider cannot ORDER BY or SUM a decimal.
class Customer { public string Id { get; set; } = ""; public string Name { get; set; } = ""; public string Tier { get; set; } = ""; }
class Product
{
    public string Sku { get; set; } = "";
    public string Name { get; set; } = "";
    public string Category { get; set; } = "";
    public double Price { get; set; }
    public int Stock { get; set; }
}
class Order
{
    public string Id { get; set; } = "";
    public string CustomerId { get; set; } = "";
    public DateTime CreatedAtUtc { get; set; }
    public double Total { get; set; }
    public string Status { get; set; } = "";
    public List<OrderLine> Lines { get; set; } = [];
}
class OrderLine
{
    public int Id { get; set; }
    public string OrderId { get; set; } = "";
    public string Sku { get; set; } = "";
    public int Quantity { get; set; }
    public double UnitPrice { get; set; }
}
class Notification
{
    public int Id { get; set; }
    public string OrderId { get; set; } = "";
    public string Channel { get; set; } = "";
    public DateTime CreatedAtUtc { get; set; }
}

class ShopDb(DbContextOptions<ShopDb> options) : DbContext(options)
{
    public DbSet<Customer> Customers => Set<Customer>();
    public DbSet<Product> Products => Set<Product>();
    public DbSet<Order> Orders => Set<Order>();
    public DbSet<OrderLine> OrderLines => Set<OrderLine>();
    public DbSet<Notification> Notifications => Set<Notification>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        b.Entity<Customer>().ToTable("customers").HasKey(x => x.Id);
        b.Entity<Product>().ToTable("products").HasKey(x => x.Sku);
        var o = b.Entity<Order>();
        o.ToTable("orders").HasKey(x => x.Id);
        o.HasIndex(x => new { x.CustomerId, x.CreatedAtUtc });
        o.HasMany(x => x.Lines).WithOne().HasForeignKey(l => l.OrderId);
        b.Entity<OrderLine>().ToTable("order_lines");
        b.Entity<Notification>().ToTable("notifications");
    }
}
